### ISSUE TITLE
Question about support for a web component

### ISSUE THREAD

**Issue by jcgueriaud1** [JetBrains/web-types#30]
Hi,

I'm not sure if I understand how the whole process is working.
My goal is to have a better idea support for a web component.
I would like to try in my side project first:
https://github.com/jcgueriaud1/xof-tree
It's web component based on open-wc starter.
Currently I don't have any support in IntelliJ.

What are the step to do this?
* I should create web-types.json (As a first step I will probably create this manually)
* I should add this in my package.json: "web-types": "dist/json/web-types.json"

I can publish it and I should have a better support in IntelliJ?

Do I need to add this in this repository or as a @web-types package? (I don't like since it's something that should be maintain in my component)
Or it something framework related (my component is using lit-html so the web-types.json should be added in lit-html)?

Thank you :)

**Comment by piotrtomiak** [comment]
Hi @jcgueriaud1! Support for web components is not yet ready. There is still a lot of work to do, so that the new version of web-types works for most of the cases, including Web Components. We are currently planning new support for 2021.2 release. Please follow https://youtrack.jetbrains.com/issue/WEB-39620 .

**Comment by jcgueriaud1** [comment]
Thanks a lot for your answer.
I'm closing this question and will track the progress.
