### ISSUE TITLE
"slots"-property in V2

### ISSUE THREAD

**Issue by BurnedToast** [JetBrains/web-types#47]
I am a bit confused with the examples and the provided packages.

I want to document a webcomponent that can be used like this:
```html
<my-panel type="primary">
  <span slot="title">Some Title</span>
  <span>This is some content</span>
</my-panel>
```
The component is written in Angular Elements.

Currently I got this web-types.json:

```json
{
  "$schema": "https://raw.githubusercontent.com/JetBrains/web-types/master/schema/web-types.json",
  "name": "my-web-types-test",
  "version": "0.0.1",
  "description-markup": "html",
  "contributions": {
    "html": {
      "elements": [
        {
          "name": "my-panel",
          "description": "Panel with a Title",
          "attributes": [
            {
              "name": "type",
              "description": "Some useful information",
              "value": {
                "type": "enum"
              },
              "values": [
                {
                  "name": "primary"
                },
                {
                  "name": "secondary"
                }
              ]
            }
          ],
          "slots": [
            {
              "name": "default"
            },
            {
              "name": "title"
            }
          ]
        }
      ]
    }
  }
}
```

The Tag and the attribute is working fine. The only Problem I have, is the missing support for the slot-suggestion. IntelliJ 2021.3.2 dont show any suggestions for the slot-attribute. Also I can not find the "slots"-property in the schema.
I found "slots" in the bootstrap-vue package: https://github.com/JetBrains/web-types/blob/master/packages/bootstrap-vue/bootstrap-vue%402.0.0.web-types.json

Is "slots" still the correct way to document slots that are provided by an webcomponent or is there a new way to do this?
Thanks for any help :)

**Comment by kawazoe** [comment]
+1, though in my case, I am using Vue 3

I would also like to know how to specify the scope like we used to be able to do in v1.

I think @piotrtomiak is probably the only person who can answer those questions. Care to chip in?

**Comment by BurnedToast** [comment]
Still searching for a solution - @piotrtomiak can you give us a hint?

**Comment by piotrtomiak** [comment]
@BurnedToast @kawazoe Sorry for the long delay, I was away. The syntax is ok and it should work. I have checked this in 2022.2 and it seems to work now, so the issue might have been fixed during my absence. Could you please let me know if this is still an issue for you with the latest version?

**Comment by BurnedToast** [comment]
Hi - it is still not working for me. I get code completion for properties and tags - but there is no suggestion for slot-names in nested HTML elements.

Using IntelliJ 2022.2.1 Build #IU-222.3739.54

Thanks for your help

**Comment by kawazoe** [comment]
@BurnedToast It kind of works for me. I get slot suggestions. My problems is with typing. Here's an example of a valid definition:

```json
{
  "name": "app-foo",
  "priority": "highest",
  "source": {
    "file": "./src/components/AppFoo.ts",
    "offset": 0
  },
  "description": "AppFoo is just a test component.",
  "slots": [
    {
      "name": "bar",
      "description": "This is a test slot that should get suggested"
    }
  ]
},
```

Something important here is the priority tag. The way the IDE merges webtypes with every other auto-completion sources means that more priority is given to language services that produces actual guarantied typings like TypeScript. This means that if your component is written in TypeScript, the entire webtypes definition will get ignored unless you specify it should use the `highest` possible priority.

This is as far as I could get it to work. If I specify types on slots, they do nothing.

**Comment by BurnedToast** [comment]
@kawazoe You get code completion when you press CTRL+Space within a `slot=""` of a nested HTML-Element?
Sorry for the stupid question - I just want to make sure I didn't misunderstand anything.

**Comment by kawazoe** [comment]
@BurnedToast Actually, playing a bit with it to try to get a good repro for you, I noticed multiple strange behaviors. Here's the whole list of tests that I did. In all cases, the component doesn't really exist and I am writing webtypes from scratch.

# Component definition
It should suggest the tag for the component. This works:
```json
{
  "name": "app-foo",
  "priority": "highest"
}
```
![image](https://user-images.githubusercontent.com/406575/189942142-f931a284-cd2c-4f8a-b185-9f69835ace13.png)

# Component description
It should resolve the description. This works:
```json
{
  "name": "app-foo",
  "priority": "highest",
  "description": "A test description for foo."
}
```
![image](https://user-images.githubusercontent.com/406575/189943001-4e347d99-61ea-4938-84c4-ad538ce48456.png)

# Props (I completely missed this issue initially)
It should suggest props. This fails:
```json
{
  "name": "app-foo",
  "priority": "highest",
  "props": [
    {
      "name": "bar",
      "description": "A test prop for foo",
      "type": ["number"]
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/406575/189943706-2f523ddf-70a1-4a18-a270-13d5c0ad161a.png)

The prop isn't listed. The description doesn't resolve. The type doesn't resolve. Even with a proper value, it shows as "unrecognized attribute or property name".

It works fine if there is an actual component for WebStorm to reference, but with only web-types, this doesn't work.

# Slots definitions
It should resolve slot names. This works:
```json
{
  "name": "app-foo",
  "priority": "highest",
  "slots": [
    {
      "name": "bar"
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/406575/189955358-659d0935-5a3e-43cc-bd6f-42e4c58f6d4a.png)

# Slots typings (this was my initial issue)
It should detect typing for parameterized slots. This fails partially:
```json
{
  "name": "app-foo",
  "priority": "highest",
  "slots": [
    {
      "name": "bar",
      "type": ["{ value: number[], func: () => string }"]
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/406575/189956265-d6b94699-ed36-40e4-b949-ce3c8d3f27c4.png)

It looks like the type is properly detected.

![image](https://user-images.githubusercontent.com/406575/189956342-d308b998-76c7-43c7-bf97-c746b0113623.png)

But it doesn't seem to apply to variables declared in the slot.

![image](https://user-images.githubusercontent.com/406575/189956572-84dfffae-2f81-4c1d-aa8b-d31546a1cf28.png)

You can also destructure more properties that doesn't exist on the type, and no error is thrown.

I have also noticed some strange type update issues. Like, I went back to the type and changed it to `Promise<unknown>`. The documentation on bar kept the old type. I had to remove the slot from the webtypes and re-add it for the type to update.

**Comment by piotrtomiak** [comment]
@kawazoe Thanks for the nice summary! Improved typing for slots will come in 2022.3, so the problem is already fixed.

`props` are specific to Vue.js framework and they are recognized only if component is contributed to `html`/`vue-components` kind (see https://github.com/JetBrains/intellij-plugins/blob/53a9dcf7e92ef7cefadee3d28cbf253210bfee39/vuejs/resources/web-types/vue%403.2.0.web-types.json#L37).

If we are talking about a Web Component, it should be contributed to `html`/`elements` kind, since it behaves as a regular HTML element. Vue does not bind to DOM element properties (like Angular), but rather to element attributes (correct me if I am wrong), thus in case of a Web Component you need to contribute `attributes`. If a binding to a `property` would be needed as in case of Angular, than you would, beside specifying list of attributes, contribute DOM object properties to `js`/`properties`.
```
{
  "name": "app-foo",
  "priority": "highest",
  "attributes": [
    {
      "name": "bar",
      "value": {
        kind: plain,
        type: "number"
      }
    }
  ],
  "js": {
     "properties": [
       {
         "name": "bar",
         "description": "A test prop for foo",
         "type": ["number"]
       }
     ]
  }
}
```
@BurnedToast Do I understand correctly, that you're trying to use a Web Component in a Vue project? It should work. If it doesn't, please share an example project I can check with.

Now, if you want to use a Web Component in a plain HTML (no framework), slots are not yet supported. Issue is here: https://youtrack.jetbrains.com/issue/WEB-46308/No-support-for-Web-Components-slot-tag .

**Comment by kawazoe** [comment]
> `props` are specific to Vue.js framework and they are recognized only if component is contributed to `html/vue-components` kind. See...

@piotrtomiak You just blew my mind here. I never realized that webtypes expected a different kind of "contribution" for vue components. I was only looking at the schema itself, and there isn't any framework specific code in there so I just assumed you always had to use "elements".

So, you're saying that by setting the "framework" property, it will extend the schema to include things like "vue-components" and "vue-directives"? I really didn't expected this initially. It's a shame that it's not part of the `$schema` itself since we do not get any suggestions or documentation while writing the types.

> Vue does not bind to DOM element properties (like Angular), but rather to element attributes (correct me if I am wrong)...

That's a very good question. I haven't looked into the vue code enough to really know about this. I always assumed attributes had to be string-typed only (as in, no matter what you put in, the DOM API will always give you a string)? Vue actually have a very complex props/attributes system. Here's what I know; maybe it will clarify things for you.

In vue, a component can declare props some attributes as props. They are strongly typed, and comes with a bunch of validations. Those props can be set statically or dynamically with `v-bind` or the `:` shorthand. Docs: https://vuejs.org/guide/components/props.html

Any key that is not assignable to a prop for that component becomes an attribute. By default, those attribues are "fallthrough" which means that they will be copied over to the root element of the component's template. This can be disabled though, and is not enabled if the template have multiple roots, this behavior is also disabled. In any case, `$attrs` is exposed inside the component and can be accessed to use those extra attributes. Docs: https://vuejs.org/guide/components/attrs.html

> If a binding to a property would be needed as in case of Angular, than you would, beside specifying list of attributes, contribute DOM object properties to js/properties.

It feels very convoluted to have three very different ways of declaring the same concept in 3 different frameworks (web-components, angular, and vue). I did not expected that.

> Improved typing for slots will come in 2022.3, so the problem is already fixed.

I assume that the behavior I am seeing in 2022.2 is normal then? You got me exited for the next release :)

**Comment by kawazoe** [comment]
@piotrtomiak I understand what you mean. After thinking about it a bit, what really surprises me now isn't the presence of the "vue-component" contribution; it's the lack of the "angular-component" (and others) contribution.

Thinking back at my first experience with web types, I found it challenging to grasp what was the proper way of defining component contributions in this format. This didn't happened because I didn't find the "vue-component" definition, but because I thought it got deprecated when you added support for angular and other frameworks. I perceived it that way because they don't use the same pattern to define contributions and it sent me in the wrong direction.

Anyway, food for thought. I appreciate the time to took to enlighten me :)

**Comment by piotrtomiak** [comment]
@kawazoe With Angular it's different again, as Angular uses selectors for contributing components and directives. There is `/js/ng-directive-element-selectors` kind. It's populated only within the Angular IDE plugin, because it's contents are a result of code analysis. Contrary to Vue or Web Components, even Angular libraries can be fully analyzed without a need for additional information like Web Types.
