### ISSUE TITLE
Better support for union types

### ISSUE THREAD

**Issue by MiniDigger** [JetBrains/web-types#51]
Just found this project in hopes of improving auto completion for my lib, its looking not bad!

Sadly I use union types for many values and I am missing auto completion for those.
e.g:
I define my props using vue3's script setup and typescript:
```ts
const props = withDefaults(
  defineProps<{
    disabled?: boolean;
    size?: "small" | "medium" | "large";
    buttonType?: "primary" | "secondary" | "red" | "transparent";
    loading?: boolean;
    to?: string | RouteLocationRaw | object;
  }>(),
  {
    disabled: false,
    size: "small",
    buttonType: "primary",
    loading: false,
    to: undefined,
  }
);
```

the generator creates this attribute for "buttonType":
```json
            {
              "name": "buttonType",
              "required": false,
              "value": {
                "kind": "expression",
                "type": "union"
              },
              "default": "\"primary\""
            },
```
loosing all the context of my union :/

**Comment by piotrtomiak** [comment]
@MiniDigger Do you mean `vue-docgen-web-types`? It uses `vue-docgen-api` package to analyze the source code. Please file an issue in `vue-styleguidist` repository. The problematic code is [if (TS_TYPE_NAME_MAP[t.type])](https://github.com/vue-styleguidist/vue-styleguidist/blob/fcdae9d332403357880363537f729e64209745c7/packages/vue-docgen-api/src/utils/getTypeFromAnnotation.ts#L62). The [`TS_TYPE_NAME_MAP`](https://github.com/vue-styleguidist/vue-styleguidist/blob/fcdae9d332403357880363537f729e64209745c7/packages/vue-docgen-api/src/utils/getTypeFromAnnotation.ts#L22) contains special rendering for `union` instead of processing each item and displaying them.
